### PR TITLE
NLogLogger - Allow NLog to capture Exception-object when only parameter (unit test)

### PR DESCRIPTION
**Pull request by snakefoot**
Unit test for #1210 (Requires NLog 4.5.4 that includes https://github.com/NLog/NLog/pull/2586)

### CODE REVIEW

**Comment by mythz** [comment]
Cheers 👍

**Comment by snakefoot** [comment]
Fast as always. Thank you for the swift merges.

**Comment by mythz** [comment]
np, FYI this change is now available from the latest v5.7.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by juniglee** [comment]
Hi @mythz , is this available on NuGet yet?

**Comment by mythz** [comment]
@juniglee No only major releases get published to NuGet (which wont be available in the immediate future), you'll need to use v5.7.1 packages on MyGet or copy the source files and use your local version.

**Pull request merged**
