### PR TITLE
Fluentvalidation6.2.1

### PR DESCRIPTION
**Pull request by wwwlicious**
ok, this is a first attempt at a backward compatible update of FluentValidation to version 6.2.1.

### CODE REVIEW

**Comment by mythz** [comment]
Hi Scott, thanks for the PR but it's too difficult to see the changes to master. Can you send a new PR with [all the commits squashed](http://stackoverflow.com/a/5201642/85785)?

**Comment by wwwlicious** [comment]
I've squashed the commits into one, I'm struggling to reproduce the white space diffs locally which are picking up a lot of unnecessary noise for which I apologise.

I've also tried to minimise the changes made to those involving code rather than arbitrary layout differences made FluentValidation but it is close to a 1:1 port as I can make it.

**Comment by mythz** [comment]
Can you run `node codegen-projs.js` in the [/build](https://github.com/ServiceStack/ServiceStack/tree/master/build) directory and commit updates to .Signed projs to fix the build?

**Comment by wwwlicious** [comment]
Afraid I can't the build results so not sure why it's still failing,

 I have an error building locally which makes it difficult to diagnose also.
"Unable to get MD5 checksum for the key file "servicestack-sn.pfx". Could not find file '<path>\servicestack-sn.pfx'.	ServiceStack.Interfaces

**Comment by mythz** [comment]
ok existing build/tests passing gives us a green light, here goes nothing...

Thanks for the massive upgrade + PR Scott! 👍

**Comment by wwwlicious** [comment]
Magic, thanks Demis, I hope I've covered everything!

**Comment by wwwlicious** [comment]
@mythz Have the packages been updated on myget? Not seeing the changes yet.

**Comment by mythz** [comment]
Apologies for the delay Scott, thought you were working off the source code binaries. 
I've just deployed the latest version to MyGet.

**Comment by wwwlicious** [comment]
Looks like not all the packages were published...?
image

**Comment by mythz** [comment]
Our CI said deployment was successful and our public MyGet feed is showing all packages were published, e.g. the [ServiceStack MyGet package](https://www.myget.org/feed/servicestack/package/nuget/ServiceStack) says it was [deployed today](https://www.myget.org/feed/servicestack/package/nuget/ServiceStack#notifications-messages) `at, 04 Mar 2017 20:32:29 GMT`. Maybe there's something caching going on with the UI you're using?

**Comment by wwwlicious** [comment]
ok thanks, caching is usually the culprit, now just have to find that cached critter! ;)

**Pull request merged**
