### PR TITLE
fix for getting bearer token when authorization header is empty

### PR DESCRIPTION
**Pull request by pblachut**
Fix for situation when authorization header is present but it is empty.

### CODE REVIEW

**Comment by mythz** [comment]
Great thx for the PR + tests! Can you also [approve the ServiceStack Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thx.

**Comment by mythz** [comment]
Hi, can you please let me know when you've [approved the CLA](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) or if you otherwise intend not to.

**Comment by pblachut** [comment]
Yes, I have approved contributor license.

**Comment by mythz** [comment]
Cheers 👍

**Pull request merged**
