### PR TITLE
QueueNames<T> does not respect QueuePrefix

### PR DESCRIPTION
**Pull request by kinstephen**
Here are the changes again. For some reason it's still showing spacing differences which are coming from the v4 version. If this isn't acceptable I can manually put the changes in if needed.

### CODE REVIEW

**Comment by mythz** [comment]
@kinstephen Can you have a look at your commits in this PR? They're rewriting every line ruining the provenance of each line. Commits should only contain the lines that are changed. Maybe you need to start with a clean fork and apply the changes manually then resubmit the PR.

**Comment by kinstephen** [comment]
This is because of the spaces differences to those lines originated from the v4 version. I will manually add the changes this time.

**Comment by mythz** [comment]
You shouldn't be copying code from v4 source files directly. Only fixes.

**Comment by kinstephen** [comment]
Demis, I wasn't. The fix was in v4. I was pulling the fix back from v4. No new code at all.

**Pull request closed without merging**
