### PR TITLE
VKCOM AuthenticateWithAccessToken

### PR DESCRIPTION
**Pull request by MherX**
subj

### CODE REVIEW

**Comment by MherX** [comment]
Implemented a login token for vk.com

**Comment by mythz** [comment]
Thanks for the PR, can you also please [approve the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) so we can merge this, thx.

**Comment by MherX** [comment]
@mythz Hi, I approved.

**Comment by mythz** [comment]
Cheers 👍

**Pull request merged**
