### PR TITLE
Added support for async PushProperty for available loggers 

### PR DESCRIPTION
**Pull request by snakefoot**
Log4net + NLog + Serilog

Help resolve https://forums.servicestack.net/t/how-to-provide-logger-with-custom-parameters-attributes/4828

### CODE REVIEW

**Comment by snakefoot** [comment]
Don't have access to TeamCity, so no clue about what 9 tests are failing.

**Comment by mythz** [comment]
Thanks for the PR! Can you also [approve the ServiceStack Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thx.

**Comment by snakefoot** [comment]
>ServiceStack Contributor License Agreement
>
>Your response has been recorded.

**Comment by mythz** [comment]
Cheers 👍

**Pull request merged**
